<#
.SYNOPSIS
    Creates folder structure from CSV file
.DESCRIPTION
    Imports folder structure from CSV file generated by Export-FolderStructure.ps1
.PARAMETER InputFile
    Path to CSV file containing folder structure
.EXAMPLE
    .\Import-FolderStructure.ps1 -InputFile 'structure.csv'
#>

param(
    [Parameter(Mandatory=$true)]
    [string]$InputFile
)

$folders = Import-Csv -Path $InputFile

foreach ($folder in $folders) {
    if (-not (Test-Path -Path $folder.Path)) {
        New-Item -Path $folder.Path -ItemType Directory | Out-Null
        Write-Host "Created folder: $($folder.Path)"
    }
}

Write-Host "Folder structure imported from $InputFile"
